# Generated by go2rpm 1
%bcond_without check

# https://github.com/satori/go.uuid
%global goipath         github.com/satori/go.uuid
%global commit          b2ce2384e17bbe0c6d34077efa39dbab3e09123b

%gometa

%global common_description %{expand:
UUID package for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        1.2.1
Release:        0.1%{?dist}
Summary:        UUID package for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(gopkg.in/check.v1)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Nov 25 16:35:48 UTC 2019 Brandon Perkins <bdperkin@gmail.com> - 1.2.1-0.1.20191125gitb2ce238
- Initial package

