# Generated by go2rpm 1
%bcond_without check

# https://github.com/aliyun/aliyun-openapi-meta
%global goipath         github.com/aliyun/aliyun-openapi-meta
%global commit          73a3ade39a109bda00ae3a80585fac98b3f3dd70

%gometa

%global common_description %{expand:
Aliyun OpenAPI Meta Data.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Aliyun OpenAPI Meta Data

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jul 28 2020 Brandon Perkins <bperkins@redhat.com> - 0-0.1.20200728git73a3ade
- Initial package of git commit 73a3ade

